"""Augmentation char de service_concerne a 50 char 2

Revision ID: 0470f278828f
Revises: c30b6d41d7b7
Create Date: 2026-06-04 15:15:40.025901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0470f278828f'
down_revision = 'c30b6d41d7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bon_livraison', schema=None) as batch_op:
        batch_op.alter_column('service_concerne',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bon_livraison', schema=None) as batch_op:
        batch_op.alter_column('service_concerne',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
