"""Ajout total_ht modele proforma

Revision ID: 09ad46bf3c38
Revises: ea092d7d19f7
Create Date: 2026-05-08 15:26:44.052832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ad46bf3c38'
down_revision = 'ea092d7d19f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_ht', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.drop_column('total_ht')

    # ### end Alembic commands ###
