"""ajout compagnie_id sur proforma et kit_proforma

Revision ID: 0e668059d764
Revises: d6b9407c3f10
Create Date: 2026-09-01 11:59:31.021422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e668059d764'
down_revision = 'd6b9407c3f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compagnie', schema=None) as batch_op:
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('adresse',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('numero_rcc',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compagnie_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_kit_proforma_compagnie_id_compagnie', 'compagnie', ['compagnie_id'], ['id'])

    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compagnie_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_proforma_compagnie_id_compagnie', 'compagnie', ['compagnie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('compagnie_id')

    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('compagnie_id')

    with op.batch_alter_table('compagnie', schema=None) as batch_op:
        batch_op.alter_column('numero_rcc',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('adresse',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('telephone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
