"""modification model proforma

Revision ID: 2302cb046506
Revises: 
Create Date: 2026-03-04 09:46:11.358905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2302cb046506'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bon_commande', schema=None) as batch_op:
        pass

    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition_paiement', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('delai_livraison', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('garantie', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.drop_column('garantie')
        batch_op.drop_column('delai_livraison')
        batch_op.drop_column('condition_paiement')

    with op.batch_alter_table('bon_commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###
