"""Ajout colonne type service dans model bondelivraison

Revision ID: 26a8c00f31b9
Revises: 09ad46bf3c38
Create Date: 2026-06-01 15:12:55.873551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a8c00f31b9'
down_revision = '09ad46bf3c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bon_livraison', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_concerne', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bon_livraison', schema=None) as batch_op:
        batch_op.drop_column('service_concerne')

    # ### end Alembic commands ###
