"""modif processus de creation de vente apres livraison

Revision ID: 2d3dfba9e78f
Revises: 7e7664e4167b
Create Date: 2026-03-31 15:31:29.344561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3dfba9e78f'
down_revision = '7e7664e4167b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bon_livraison_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vente_bon_livraison', 'bon_livraison', ['bon_livraison_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vente_bon_livraison', type_='foreignkey')
        batch_op.drop_column('bon_livraison_id')

    # ### end Alembic commands ###
