"""modif blockit en block_kit

Revision ID: 36be9af5e20b
Revises: ef57ee2e6112
Create Date: 2026-03-18 13:14:24.348409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36be9af5e20b'
down_revision = 'ef57ee2e6112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bloc__kit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloc__kit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kit_id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['kit_proforma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
