"""Ajout colonne telephone à usercls

Revision ID: 4ec07dce67a9
Revises: e8dd389b7ea4
Create Date: 2026-05-07 17:00:40.356102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec07dce67a9'
down_revision = 'e8dd389b7ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proforma_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('proforma_comment', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('proforma_comment2', sa.String(length=500), nullable=True))

    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proforma_comment2', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.drop_column('proforma_comment2')

    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.drop_column('proforma_comment2')
        batch_op.drop_column('proforma_comment')
        batch_op.drop_column('proforma_title')

    # ### end Alembic commands ###
