"""fix constraint duplicate dans ajout stock 3

Revision ID: 54a21dcb0ebf
Revises: b15501a75a52
Create Date: 2026-02-20 10:48:58.363165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a21dcb0ebf'
down_revision = 'b15501a75a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_produit_lot_magasin_conditionnement'), type_='unique')
        batch_op.create_unique_constraint('uix_stock_unique', ['produit_id', 'magasin_id', 'type_conditionnement'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint('uix_stock_unique', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_produit_lot_magasin_conditionnement'), ['produit_id', 'magasin_id', 'type_conditionnement'])

    # ### end Alembic commands ###
