"""mise a jour des table pour render

Revision ID: 56728bd31654
Revises: e5542b971222
Create Date: 2026-02-16 11:57:55.637695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56728bd31654'
down_revision = 'e5542b971222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('type_conditionnement',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('type_conditionnement',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###
