"""modif colonne vente 

Revision ID: 68ca655f7b08
Revises: 
Create Date: 2026-02-09 12:08:06.782176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ca655f7b08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annule', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.drop_column('annule')

    # ### end Alembic commands ###
