"""Augmentation taille condition_paiement

Revision ID: 6ecbaff03906
Revises: b606a9b27238
Create Date: 2026-04-22 08:21:25.115065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecbaff03906'
down_revision = 'b606a9b27238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.alter_column('proforma_title',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('proforma_comment',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('condition_paiement',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('delai_livraison',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('garantie',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('attn',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.alter_column('attn',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('garantie',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('delai_livraison',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('condition_paiement',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('proforma_comment',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('proforma_title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
