"""Ajout stock_id dans ligne_achat

Revision ID: 7e7664e4167b
Revises: e1f526ffc29d
Create Date: 2026-03-30 15:53:27.105770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7664e4167b'
down_revision = 'e1f526ffc29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligne_achat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ligne_achat_stock_id', 'stock', ['stock_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligne_achat', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ligne_achat_stock_id', type_='foreignkey')
        batch_op.drop_column('stock_id')

    # ### end Alembic commands ###
