"""fix enum nullable=False

Revision ID: 88944b870a2b
Revises: a412a05b24ce
Create Date: 2026-02-14 19:36:16.245608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88944b870a2b'
down_revision = 'a412a05b24ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('type_conditionnement',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('type_conditionnement',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###
