"""ajout colonne conditionnement dans model

Revision ID: a412a05b24ce
Revises: f84e101b7149
Create Date: 2026-02-14 18:12:59.013717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a412a05b24ce'
down_revision = 'f84e101b7149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_conditionnement', sa.Enum('CARTON', 'PAQUET', 'UNITE', name='typeconditionnement'), nullable=True))
        batch_op.drop_constraint(batch_op.f('uix_produit_lot'), type_='unique')
        batch_op.create_unique_constraint('uix_produit_lot_magasin_conditionnement', ['produit_id', 'numero_lot', 'magasin_id', 'type_conditionnement'])

    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.alter_column('vendeur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('compagnie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.alter_column('compagnie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vendeur_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint('uix_produit_lot_magasin_conditionnement', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_produit_lot'), ['produit_id', 'numero_lot'])
        batch_op.drop_column('type_conditionnement')

    # ### end Alembic commands ###
