"""modif model stock enlever numer_lot

Revision ID: a8d2f6bde721
Revises: 
Create Date: 2026-02-25 15:51:48.046258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d2f6bde721'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('numero_lot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_lot', sa.VARCHAR(length=120), nullable=False))

    # ### end Alembic commands ###
