"""fix constraint duplicate dans ajout stock

Revision ID: b15501a75a52
Revises: 56728bd31654
Create Date: 2026-02-20 10:07:07.144435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15501a75a52'
down_revision = '56728bd31654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_produit_lot_magasin_conditionnement'), type_='unique')
        batch_op.create_unique_constraint('uix_produit_lot_magasin_conditionnement', ['produit_id', 'magasin_id', 'type_conditionnement'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint('uix_produit_lot_magasin_conditionnement', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_produit_lot_magasin_conditionnement'), ['produit_id', 'numero_lot', 'magasin_id', 'type_conditionnement'])

    # ### end Alembic commands ###
