"""Creation certificat reparation model

Revision ID: b465127c5051
Revises: ef57ee2e6112
Create Date: 2026-03-23 08:53:23.892671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b465127c5051'
down_revision = 'ef57ee2e6112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificat_reparation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_certificat', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_reparation', sa.Date(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('technicien', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificat_reparation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificat_reparation_numero_certificat'), ['numero_certificat'], unique=True)

    op.create_table('reparation_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taches_effectuees', sa.Text(), nullable=False),
    sa.Column('cout_reparation', sa.Float(), nullable=True),
    sa.Column('garantie_mois', sa.Integer(), nullable=True),
    sa.Column('certificat_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificat_id'], ['certificat_reparation.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reparation_detail')
    with op.batch_alter_table('certificat_reparation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificat_reparation_numero_certificat'))

    op.drop_table('certificat_reparation')
    # ### end Alembic commands ###
