"""ajout date_commande dans bon_commande

Revision ID: b606a9b27238
Revises: f0f4df668232
Create Date: 2026-04-10 11:36:46.967697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b606a9b27238'
down_revision = 'f0f4df668232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bon_commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_commande', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bon_commande', schema=None) as batch_op:
        batch_op.drop_column('date_commande')

    # ### end Alembic commands ###
