"""Augmentation char de service_concerne a 50 char

Revision ID: c30b6d41d7b7
Revises: dd46b931b53d
Create Date: 2026-06-04 14:58:27.756657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30b6d41d7b7'
down_revision = 'dd46b931b53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.alter_column('service_concerne',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.alter_column('service_concerne',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
