"""Ajout colonne numero lot a model stock

Revision ID: c69e8e85668b
Revises: dd7e60a10984
Create Date: 2026-03-30 11:08:53.139647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69e8e85668b'
down_revision = 'dd7e60a10984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_lot', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('numero_lot')

    # ### end Alembic commands ###
