"""new modele create certificat installation

Revision ID: cd403a2d6cd8
Revises: 5333f67b1db7
Create Date: 2026-06-15 15:00:05.139746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd403a2d6cd8'
down_revision = '5333f67b1db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificat_installation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('attn', sa.String(length=400), nullable=True),
    sa.Column('ref_certif', sa.String(length=200), nullable=False),
    sa.Column('numero_serie', sa.String(length=200), nullable=True),
    sa.Column('ville', sa.String(length=200), nullable=True),
    sa.Column('comment1', sa.String(length=400), nullable=True),
    sa.Column('comment2', sa.String(length=400), nullable=True),
    sa.Column('date_installation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_certif')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificat_installation')
    # ### end Alembic commands ###
