"""new modele create ligne certif installation

Revision ID: d6b9407c3f10
Revises: cd403a2d6cd8
Create Date: 2026-06-15 15:35:10.146364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b9407c3f10'
down_revision = 'cd403a2d6cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ligne_certificat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificat_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('numero_serie_produit', sa.String(length=200), nullable=True),
    sa.Column('observation', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['certificat_id'], ['certificat_installation.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ligne_certificat')
    # ### end Alembic commands ###
