"""Ajout colonne service pour proforma

Revision ID: dd46b931b53d
Revises: 26a8c00f31b9
Create Date: 2026-06-02 10:39:28.255557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd46b931b53d'
down_revision = '26a8c00f31b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_concerne', sa.String(length=20), nullable=True))

    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_concerne', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.drop_column('service_concerne')

    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.drop_column('service_concerne')

    # ### end Alembic commands ###
