"""modif certificat reparation model 

Revision ID: dd7e60a10984
Revises: b465127c5051
Create Date: 2026-03-23 10:16:13.408655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7e60a10984'
down_revision = 'b465127c5051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparation_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_serie', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparation_detail', schema=None) as batch_op:
        batch_op.drop_column('numero_serie')

    # ### end Alembic commands ###
