"""modif du model ligneBonLivraison pour relier avec le stock

Revision ID: e1f526ffc29d
Revises: c69e8e85668b
Create Date: 2026-03-30 12:40:47.131179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f526ffc29d'
down_revision = 'c69e8e85668b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligne_bon_livraison', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ligne_bon_livraison_stock', 'stock', ['stock_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligne_bon_livraison', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ligne_bon_livraison_stock', type_='foreignkey')
        batch_op.drop_column('stock_id')

    # ### end Alembic commands ###
