"""Ajout colonne remise to proforma and kitproforma

Revision ID: ea092d7d19f7
Revises: 4ec07dce67a9
Create Date: 2026-05-08 07:17:05.909197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea092d7d19f7'
down_revision = '4ec07dce67a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remise', sa.Float(), nullable=True))

    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remise', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.drop_column('remise')

    with op.batch_alter_table('kit_proforma', schema=None) as batch_op:
        batch_op.drop_column('remise')

    # ### end Alembic commands ###
