"""Ajout de deux colonne dans modele proformat

Revision ID: f0f4df668232
Revises: fc10527c5f4d
Create Date: 2026-04-03 08:28:39.931180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f4df668232'
down_revision = 'fc10527c5f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proforma_title', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('proforma_comment', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.drop_column('proforma_comment')
        batch_op.drop_column('proforma_title')

    # ### end Alembic commands ###
