"""Ajout colonne reference paiement dans model paiement

Revision ID: f84e101b7149
Revises: 
Create Date: 2026-02-12 11:16:43.753351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84e101b7149'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_paiement', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.drop_column('reference_paiement')

    # ### end Alembic commands ###
