"""remove_compagnie_id_from_produit

Revision ID: fc10527c5f4d
Revises: 82a7a69e2896
Create Date: 2026-04-02 12:20:12.272302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc10527c5f4d'
down_revision = '82a7a69e2896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_produit_compagnie_id'), type_='foreignkey')
        batch_op.drop_column('compagnie_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compagnie_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_produit_compagnie_id'), 'vendeur_compagnie', ['compagnie_id'], ['id'])

    # ### end Alembic commands ###
