"""ajout colonne attn dans proforma model

Revision ID: fcf7b73b0ba2
Revises: 
Create Date: 2026-03-05 10:17:24.173685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf7b73b0ba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attn', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.drop_column('attn')

    # ### end Alembic commands ###
